# This file contains example ServiceMonitor configurations for various components.
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: node-exporter
    app.kubernetes.io/part-of: kube-prometheus
  name: node-exporter
  namespace: chronosphere
spec:
  endpoints:
    - port: "metrics" # This should match the port name in the node-exporter service
      # replace instance label with node name otherwise it will be the exporter pod name
      relabelings:
        - action: replace
          regex: (.*)
          replacement: $1
          sourceLabels:
            - __meta_kubernetes_pod_node_name
          targetLabel: instance
      scheme: http
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      app.kubernetes.io/component: metrics
      app.kubernetes.io/name: prometheus-node-exporter
      app.kubernetes.io/part-of: prometheus-node-exporter
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-state-metrics
  namespace: chronosphere
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/part-of: kube-prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-state-metrics
  endpoints:
    - port: http # This should match the port name in kube-state-metrics service
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dcgm-exporter
  namespace: chronosphere
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: dcgm-exporter
    app.kubernetes.io/part-of: gke-managed-system
spec:
  selector:
    matchLabels:
      app: dcgm-exporter
  endpoints:
    - port: metrics # This should match the port name in dcgm-exporter service
      # replace instance label with node name otherwise it will be the exporter pod name
      relabelings:
        - action: replace
          regex: (.*)
          replacement: $1
          sourceLabels:
            - __meta_kubernetes_pod_node_name
          targetLabel: instance
      scheme: http
      interval: 30s
  jobLabel: app.kubernetes.io/name
